server:
  port: 8081

---
spring:
  profiles: jms-template, jms-listener
  # The values given here are actually the default values. But they are explicitly
  # set here as an example of setting the Artemis properties.
  jms:
    template:
      receive-timeout: 2
  artemis:
    broker-host: localhost
    broker-port: 61616
    user: tacoweb
    password: letm31n
    embedded:
      enabled: false

---
spring:
  profiles: kafka-listener

  kafka:
    bootstrap-servers:
      - localhost:9092
    template:
      default-topic: tacoz.orders.topic
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: tacoz_kitchen
      properties:
        spring.json.trusted.packages: tacoz-ms





